<a href="https://colab.research.google.com/github/KIrie-0217/Python_practice/blob/master/Python%E5%8B%89%E5%BC%B7%E4%BC%9A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python勉強会

1. python基本
2. 画像処理の基本・必要な物
3. 画像処理してみる 

## 1. Python基本

- コメントアウトは＃
- 型の指定は不要！
- 変数の同時挿入が便利


### 変数

Pythonはメチャクチャ簡単、型を指定しなくても勝手に推論してくれる

In [ ]:
a = 1
b = 1.2
c = "Tenma"
d = [1,2,3]

#型を指定して代入すれば当然型指定もできる
e = float(1)


print("a is" ,a,":",type(a))
print("b is" ,b,":",type(b))
print("c is" ,c,":",type(c))
print("d is" ,d,":",type(d))
print("e is" ,e,":",type(e))

a is 1 : <class 'int'>
b is 1.2 : <class 'float'>
c is Tenma : <class 'str'>
d is [1, 2, 3] : <class 'list'>
e is 1.0 : <class 'float'>


変数の同時挿入が便利

In [ ]:
a,b,c = 1,1.2,"Tenma"

print("a is" ,a,":",type(a))
print("b is" ,b,":",type(b))
print("c is" ,c,":",type(c))

a is 1 : <class 'int'>
b is 1.2 : <class 'float'>
c is Tenma : <class 'str'>


### 制御構文

- if
- for
- while


Pythonではインデントでネストしていく  
ちなみにPythonのforループはめちゃくちゃ遅い  
多重ネストはしすぎないほうがいい

#### if

In [ ]:
a = 1
b = 2

if b > a:
  print("b > a")


b > a


#### for

In [ ]:
c = [1,2,3,4,5,"end"]

for i in c:
  print(i)

#range型にするとn番目の指定がしやすい
for i in range(len(c)):
  print(i,":",c[i])

1
2
3
4
5
end
0 : 1
1 : 2
2 : 3
3 : 4
4 : 5
5 : end


while

In [ ]:
# while hoge : hogeがTrueならループ
d = 0
while d < 4:
  print(d)
  d += 1

0
1
2
3


### 関数

- def 関数名(引数): 処理 で作成

In [ ]:
def Nakigoe(animal):
  if animal["Category"] is "dog":
    nakigoe = "bow wow"
  
  elif animal["Category"] is "bird":
    nakigoe = "chirp chirp"

  animal["Nakigoe"] = nakigoe
  return animal

In [ ]:
Tenma = {"Age":3, "Category":"dog"}
print(Nakigoe(Tenma))



{'Age': 3, 'Category': 'dog', 'Nakigoe': 'bow wow'}


- globalを入れることでglobal関数として処理ができる

In [ ]:
def not_global(values):
  a = 1
  values += a
  return values

def is_global(values):
  global a 
  a = 1
  values += a
  return values 

In [ ]:
a = 2
b = 7

# global関数に指定しないとaの値は変わらない
c = not_global(b)
print(a,c)

# global関数に指定するとaの値も変わる
c = is_global(b)
print(a,c)

2 8
1 8


## 2. 画像処理の基本・必要なもの

- numpy : 行列計算には必須・リスト型より超便利,deep learningなどに
- matplotlib : グラフツール・画像処理ではそんな使わないかも
- OpenCV : 画像表示・処理、必須アイテム

### import

In [2]:
# numpy をnpという名前でインポート
import numpy as np

# matplotlibをpltという名前でインポート
import matplotlib as plt

# OpenCV import
import cv2 


### numpy


In [10]:
# 行列の定義

# 1x3 行列 
a = np.array([1,2,3])

# 3x3 行列
b = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
              ])


print("a:",a)
print("---")
print("b:",b)


a: [1 2 3]
---
b: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 行列のサイズ 変数名.size
print("SIZE:",b.size)

# 行列のランク 変数名.ndim
print("RANK:",b.ndim)

# 行列の形 変数名.shape
print("SHAPE:",b.shape)

SIZE: 9
RANK: 2
SHAPE: (3, 3)


In [4]:
# 要素が0の3x3行列
c = np.zeros((3,3))

# 要素が1の2x3行列
d = np.ones((2,3))

# 任意の値の4x3行列
e = np.full((4,3),4)

# 単位行列
f = np.eye(4)

# ランダムな値の行列
g = np.random.random((3,3))

print("c:",c)
print("---")
print("d:",d)
print("---")
print("e:",e)
print("---")
print("f:",f)
print("---")
print("g:",g)

c: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---
d: [[1. 1. 1.]
 [1. 1. 1.]]
---
e: [[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
---
f: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---
g: [[0.08082169 0.67712219 0.10242365]
 [0.3970441  0.27015189 0.29370846]
 [0.8077579  0.85050149 0.44616983]]


#### 行列計算

In [6]:
a = np.array([
              [0,1,2],
              [3,4,5],
              [6,7,8]
              ])
b = np.eye(3)
c = np.full((3,3),2)

# 足し算
print(a+b)
print("---")
# 引き算
print(a-b)
print("---")
# 掛け算
print(a*b)
print("---")
# 割り算
print(a/c)
print("---")
# 要素ごとにn乗
print(a ** 2)
print("---")
# 要素ごとにn倍
print(a*2)

[[1. 1. 2.]
 [3. 5. 5.]
 [6. 7. 9.]]
---
[[-1.  1.  2.]
 [ 3.  3.  5.]
 [ 6.  7.  7.]]
---
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]
---
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
---
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
---
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


#### 統計量

In [10]:
# 平均
print(a.mean())

# 分散
print(a.var())

# 標準偏差
print(a.std())

# 最大
print(a.max())

# 最小
print(a.min())

# 軸ごと
print(a.min(axis = 1))
print(a.min(axis = 0))

4.0
6.666666666666667
2.581988897471611
8
0
[0 3 6]
[0 1 2]


### matplotlib

[これ](https://colab.research.google.com/github/chainer/tutorials/blob/master/ja/12_Introduction_to_Matplotlib.ipynb#scrollTo=nD6RSWpgWBpz)が参考になる。割愛

### OpenCV